---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-profec-net
  namespace: default
spec:
  secretName: local-profec-net-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.profec.net"
  dnsNames:
  - "profec.net"
  - "*.profec.net"
