---
- name: Install Developer packages (dnf)
  become: true
  become_method: sudo
  dnf:
    pkg:
      - code
      - dbeaver-ce
      - git
      # - MariaDB / MySQL
      # - Postgres?
      # - Redix / Mongo?
    state: latest

# - name: Add the flathub flatpak repository remote to the user installation
#   community.general.flatpak_remote:
#     name: flathub
#     state: present
#     flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
#     method: user
