---
- hosts: morpheus
  become: true
  tasks:

  - name: Update repository cache
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Install proxmoxer
    apt:
      name:
      - python3-proxmoxer
      state: latest
