---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: profec-net
  namespace: default
spec:
  secretName: profec-net-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.profec.net"
  dnsNames:
  - "profec.net"
  - "*.profec.net"
